export function configure(config) {
    
    config.globalResources(['./elements/navigation/nav-header']);
    config.globalResources(['./elements/navigation/main-nav']);
    config.globalResources(['./elements/navigation/sub-nav']);
    config.globalResources(['./elements/chart/any-chart']);
    config.globalResources(['./elements/rule/rule']);
    config.globalResources(['./elements/rule-set/rule-set']);
    config.globalResources(['./elements/rule-set/rule-set-item']);
    config.globalResources(['./elements/indicator/indicator']);
    config.globalResources(['./elements/strategy/strategy-admin']);
    config.globalResources(['./attributes/first-letter-span']);
    config.globalResources(['./value-converters/blob-to-url']);
    config.globalResources(['./value-converters/filelist-to-array']);
    config.globalResources(
        './elements/article/article',
        './elements/article/strategy',
        './elements/article/article-block',
        './elements/article//heading-block',
        './elements/article//paragraph-block',
        './elements/article/image-block',
        './elements/article/ordered-list-block',
        './elements/article/block-actions',
        './elements/article/new-block'
    );
    config.globalResources(
        './elements/article-parts/article-parts',
        './elements/article-parts/article-part-paragraph',
        './elements/article-parts/article-part-heading',
        './elements/article-parts/article-part-actions',
        './elements/article-parts/article-part-image',
        './elements/article-parts/article-part-list',
        './elements/article-parts/article-part-new'
    );
}
