// <auto-generated />
namespace dream.walker.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterStrategy_AddUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterStrategy_AddUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201611282052436_AlterStrategy_AddUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
