// <auto-generated />
namespace dream.walker.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreatevStrategyRuleSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatevStrategyRuleSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291254010_CreatevStrategyRuleSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
